### ISSUE TITLE
RuntimeError encountered when training a text2emotion lstm classifier

### ISSUE THREAD

**Issue by pengzhansun** [optas/artemis#14]
I'm trying to train an lstm based txt2emo classifier, and use the code provided in notebook. But unfortunately I got stuck in the following error and have no idea anything wrong.

Traceback (most recent call last):
  File "/ibex/scratch/sunp/project/artemis/artemis/notebooks/deep_nets/emotions/train_text2emo.py", line 170, in <module>
    single_epoch_train(model, dataloaders['train'], args.use_imgs, criterion, optimizer, device)
  File "/ibex/scratch/sunp/project/artemis/artemis/neural_models/text_emotional_clf.py", line 55, in single_epoch_train
    loss.backward()
  File "/home/sunp/ibex-miniconda-install/ENTER/envs/artemislic/lib/python3.6/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/sunp/ibex-miniconda-install/ENTER/envs/artemislic/lib/python3.6/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1024, 31, 256]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Is this caused by the python version or network architecture? It would be nice of you if you can help to check it. Thanks in advance:)

**Comment by pengzhansun** [comment]
just change the torch and torchvision version as the same one mentioned by author in the readme file. The version of torch and torchvision downloaded from the script "pip install -e ." is not the right one.
